version: 0.2

env:
  variables:
    BUCKET: "flow-balance"

phases:
  pre_build:
    commands:
      - sudo apt-get -y update
      - sudo apt-get -y upgrade
      - sudo pip install virtualenv
      - sudo pip install --upgrade pip
      - sudo apt-get install -y findutils zip git
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true

  build:
    commands:
      - build/build-pack lambda/*
  
  post_build:
    commands:
      - aws s3 sync srv s3://$BUCKET/srv
      - build/sync-lambda lambda/*

# vim: set ts=2 sw=2:
